version: '3'
services:
  db:
    image: mongo
    container_name: bookclub-api-db
    ports:
      - 27017:27017

  web:
    image: bookclub-api
    container_name: bookclub-api
    build: .
    ports:
      - 5001:5001
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017